# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-22 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
